### ISSUE TITLE
Update POST/cttreasury/deposit endpoint

### ISSUE THREAD

**Issue by freitasgouvea** [solid-world/solid-world-dao-contracts-frontend#59]
- Update endpoint path name from `scttreasury/deposit` to `cttreasury/deposit`
- Adjust deposit flow and parameters if its necessary

**Comment by jeffprestes** [comment]
I am afraid this issue would belong to API ( https://github.com/solid-world/solid-world-marketplace-backend ) .
Am I correct?

**Comment by freitasgouvea** [comment]
Oh yes, its related to the backend
